# Python for DataScience

## Numpy

In [15]:
#IMPORTATION DE NUMPY
import numpy as np

In [67]:
#DECLARATION LISTE 1D
a = np.array([1, 4, 2, 5, 3])
print(a)

[1 4 2 5 3]


In [69]:
#DECLARATION LIST MULTI TYPES
a = np.array([3.14, 4, 2, 3])
print(a)

[3.14 4.   2.   3.  ]


In [17]:
#DECLARATION LIST DE TYPES FLOAT32
a = np.array([1, 2, 3, 4], dtype='float32')
print(a)

[1. 2. 3. 4.]


In [68]:
#
a = np.array([range(i, i + 3) for i in [1, 3, 5]])
print(a)

[[1 2 3]
 [3 4 5]
 [5 6 7]]


In [20]:
a = np.array([[1, 2, 3], [3, 4, 5], [5, 6, 7]])
print(a)

[[1 2 3]
 [3 4 5]
 [5 6 7]]


In [22]:
# Create a length-10 integer array filled with zeros
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [23]:
# Create a 3x5 floating-point array filled with ones
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [24]:
# Create a 3x5 array filled with 3.14
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [25]:
# Create an array filled with a linear sequence
 # Starting at 0, ending at 20, stepping by 2
 # (this is similar to the built-in range() function)
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [26]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [29]:
# Create a 3x3 array of uniformly distributed
# random values between 0 and 1
np.random.random((3, 3)) # Comment faire pour voir toutes les distribution proposées par NumPy?

array([[0.19755325, 0.08805385, 0.34504957],
       [0.2803965 , 0.7578879 , 0.74680335],
       [0.79087058, 0.91805729, 0.86201715]])

In [28]:
# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
np.random.normal(0, 1, (3, 3))

array([[ 0.67343618, -0.76170359,  0.14037979],
       [ 1.32194   , -1.34276387, -0.30120838],
       [ 0.26235486,  1.47758602, -0.1596058 ]])

In [ ]:
b

In [31]:
np.random.seed(0) # seed for reproducibility

In [32]:
x1 = np.random.randint(10, size=6) # One-dimensional array
x1

array([5, 0, 3, 3, 7, 9])

In [33]:
x2 = np.random.randint(10, size=(3, 4)) # Two-dimensional array
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [34]:
x3 = np.random.randint(10, size=(3, 4, 5)) # Three-dimensional array print("x3 ndim: ", x3.ndim)
x3

array([[[8, 1, 5, 9, 8],
        [9, 4, 3, 0, 3],
        [5, 0, 2, 3, 8],
        [1, 3, 3, 3, 7]],

       [[0, 1, 9, 9, 0],
        [4, 7, 3, 2, 7],
        [2, 0, 0, 4, 5],
        [5, 6, 8, 4, 1]],

       [[4, 9, 8, 1, 1],
        [7, 9, 9, 3, 6],
        [7, 2, 0, 3, 5],
        [9, 4, 4, 6, 4]]])

In [38]:
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)
print("dtype:", x3.dtype)
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

x3 shape: (3, 4, 5)
x3 size:  60
dtype: int32
itemsize: 4 bytes
nbytes: 240 bytes


## Array Slicing - 1 dimension

In [79]:
# 1. Créer un tableau d’entier allant de 0 à 9
tab = np.arange(10)
print("1. ", tab)
# 2. Récupérer les 5 premiers éléments
print("2. ", tab[:5])
# 3. Récupérer les éléments après le 5
print("3. ", tab[6:])
# 4. Récupérer les éléments de 4 à 7
print("4. ", tab[4:8])
# 5. Récupérer les paires
print("5. ", tab[::2])
# 6. Récupérer les impaires (sans zéro)
print("6. ", tab[1::2])
# 7. Les trois derniers éléments
print("7. ", tab[-3:])
# 8. Les éléments par ordre inverse
print("8. ", tab[::-1])
# 9. Les 5 premiers en ordre inverse
print("9. ", tab[4::-1])
# 10. Tout sélectionner avec la syntaxe de slicing
print("10.", tab[:])

1.  [0 1 2 3 4 5 6 7 8 9]
2.  [0 1 2 3 4]
3.  [6 7 8 9]
4.  [4 5 6 7]
5.  [0 2 4 6 8]
6.  [1 3 5 7 9]
7.  [7 8 9]
8.  [9 8 7 6 5 4 3 2 1 0]
9.  [4 3 2 1 0]
10. [0 1 2 3 4 5 6 7 8 9]


In [66]:
tab[:4:-1]

array([9, 8, 7, 6, 5])

In [80]:
tab[-3:]

array([7, 8, 9])

## Array slicing 2 dimensions

In [101]:
#EX1 (BEST ONE!)
np.arange(9,0,-1).reshape(9,1)

array([[9],
       [8],
       [7],
       [6],
       [5],
       [4],
       [3],
       [2],
       [1]])

In [74]:
#EX1
np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [84]:
#EX1
tab = np.array([range(i, i-3, -1) for i in (9, 6, 3) ])
tab

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [103]:
tab[:,0:1]

array([[9],
       [6],
       [3]])

In [102]:
tab[:,0, np.newaxis]

array([[9],
       [6],
       [3]])

In [96]:
tab[:,1:3 ]

array([[8, 7],
       [5, 4],
       [2, 1]])

In [92]:
tab[0:2, 0:2]

array([[9, 8],
       [6, 5]])

In [91]:
tab[0:3, 0]

array([9, 6, 3])

In [90]:
#EX3
tab[::-1]

array([[3, 2, 1],
       [6, 5, 4],
       [9, 8, 7]])

## Views

In [104]:
x1 = np.arange(10, 100, 10).reshape(3, 3)
x1

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [105]:
x2 = x1[1:, 1:]
x2

array([[50, 60],
       [80, 90]])

In [107]:
x2[0,0] = 99
x2

array([[99, 60],
       [80, 90]])

In [108]:
x1

array([[10, 20, 30],
       [40, 99, 60],
       [70, 80, 90]])

La modification du tableau numpy **x2** modifie également le tableau numpy **x1**

## Copy

In [110]:
x1 = np.arange(10, 100, 10).reshape(3, 3)
x1

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [111]:
x2 = x1[1:, 1:].copy()
x2

array([[50, 60],
       [80, 90]])

In [112]:
x2[0,0] = 99
x2

array([[99, 60],
       [80, 90]])

In [113]:
x1

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])