# Pynative Pandas Exos

In [1]:
import numpy as np

In [19]:
#ex1
tab = [[64392, 31655],[32579, 0],[49248, 462],[0,0]]
tab2 = np.empty([4, 2], dtype = np.uint32)
print(tab2)
ntab = np.array(tab)
print(ntab)
print()
print("array shape :", ntab.shape)
print("array dim :", ntab.ndim)
print("length of each element of array in bytes : ", tab2.itemsize)

[[         0  805306368]
 [ 874106521 4026533881]
 [         2          0]
 [         0     131072]]
[[64392 31655]
 [32579     0]
 [49248   462]
 [    0     0]]

array shape : (4, 2)
array dim : 2
length of each element of array in bytes :  4


In [20]:
#ex2
np.arange(100, 200, 10).reshape(5, 2)

array([[100, 110],
       [120, 130],
       [140, 150],
       [160, 170],
       [180, 190]])

In [28]:
#ex3
sampleArray = np.array([[11 ,22, 33], [44, 55, 66], [77, 88, 99]])
print(sampleArray)
print()
print(sampleArray[:, 1])

[[11 22 33]
 [44 55 66]
 [77 88 99]]

[22 55 88]


In [38]:
#ex4
sampleArray = np.array([[3 ,6, 9, 12], [15 ,18, 21, 24], 
[27 ,30, 33, 36], [39 ,42, 45, 48], [51 ,54, 57, 60]])
print(sampleArray)
print()
print(sampleArray[ ::2 , 1::2 ])

[[ 3  6  9 12]
 [15 18 21 24]
 [27 30 33 36]
 [39 42 45 48]
 [51 54 57 60]]

[[ 6 12]
 [30 36]
 [54 60]]


In [45]:
#ex5
arrayOne = np.array([[5, 6, 9], [21 ,18, 27]])
arrayTwo = np.array([[15 ,33, 24], [4 ,7, 1]])

print(arrayOne)
print()
print(arrayTwo)
print()
print("ADD")
print("---")
a = arrayOne + arrayTwo
print(a)
print("SQUARE ROOT")
print("---")
print(a**2)

[[ 5  6  9]
 [21 18 27]]

[[15 33 24]
 [ 4  7  1]]

ADD
---
[[20 39 33]
 [25 25 28]]
SQUARE ROOT
---
[[ 400 1521 1089]
 [ 625  625  784]]


In [50]:
#ex6
tab = np.arange(10, 34).reshape(8, 3)
print(tab)
print()
print(np.split(tab, 4))

[[10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]
 [22 23 24]
 [25 26 27]
 [28 29 30]
 [31 32 33]]

[array([[10, 11, 12],
       [13, 14, 15]]), array([[16, 17, 18],
       [19, 20, 21]]), array([[22, 23, 24],
       [25, 26, 27]]), array([[28, 29, 30],
       [31, 32, 33]])]


In [65]:
#ex7
tab = np.array([[34,43,73],[82,22,12],[53,94,66]])
print(tab)
print()
print(tab[ : , ::-1 ])
print()
print(tab[ 1: , : ])

print()
print(tab[:,1].argsort())
print(tab[:,1])

[[34 43 73]
 [82 22 12]
 [53 94 66]]

[[73 43 34]
 [12 22 82]
 [66 94 53]]

[[82 22 12]
 [53 94 66]]

[1 0 2]
[43 22 94]
