In [1]:
import numpy as np

# Algorithme avancés

__Numpy__ ne contient seulement 1 seul type par matrix!

In [4]:
my_array = np.array([1, 2, 3])
print(my_array)
print(my_array.dtype)

[1 2 3]
int64


In [5]:
my_array = np.array([1, 2, 3, 3.14])
print(my_array)
print(my_array.dtype)

[1.   2.   3.   3.14]
float64


In [6]:
my_array = np.array([1, 2, 3, 3.14, '5'])
print(my_array)
print(my_array.dtype)

['1' '2' '3' '3.14' '5']
<U32


Nous pouvons indiquer et forcer le type de la matrix avec __dtype__

In [7]:
my_array = np.array([1, 2, 3, 3.14], dtype=int)
print(my_array)
print(my_array.dtype)

[1 2 3 3]
int64


In [8]:
my_array = np.array([1, 2, 3, 3.14, '6'], dtype=int)
print(my_array)
print(my_array.dtype)

[1 2 3 3 6]
int64


In [17]:
a1 = np.array([1, 2, 3])
print(a1)
print(a1.ndim)
a1.shape

[1 2 3]
1


(3,)

In [18]:
a2 = np.array([[1, 2, 3]])
print(a2)
print(a2.ndim)
a2.shape

[[1 2 3]]
2


(1, 3)

In [19]:
a3 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a3)
print(a3.ndim)
a3.shape

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2


(3, 3)

In [20]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [28]:
np.zeros(shape=(5, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [29]:
np.ones(shape=(5, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [37]:
np.full(shape=(5, 3), fill_value=4)

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [33]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [44]:
np.linspace(0, 100, 6)

array([  0.,  20.,  40.,  60.,  80., 100.])

In [47]:
np.random.random((5, 2))

array([[0.28331228, 0.69153111],
       [0.60151774, 0.71013947],
       [0.57091937, 0.8013144 ],
       [0.5114715 , 0.14487536],
       [0.07610782, 0.66110596]])

In [46]:
np.random.randint(0,10, (5, 2))

array([[5, 2],
       [9, 5],
       [1, 5],
       [3, 7],
       [6, 8]])

In [50]:
np.random.randint(0, 10, (5, 2))

array([[9, 6],
       [7, 9],
       [0, 1],
       [5, 7],
       [0, 7]])

Create a 3x3 array of normally distributed random values with mean 0 and standard deviation 1

In [53]:
np.random.normal(0, 1, (3, 3))

array([[ 1.49927293,  0.33212384,  0.27935416],
       [ 0.79598841,  0.17714657,  0.29883195],
       [-1.09081709,  0.76409115,  1.24718748]])

In [56]:
a = 34j
print(a)
type(a)

34j


complex

In [77]:
np.random.seed(1)
test = np.random.randint(0, 100, 50)
test

array([37, 12, 72,  9, 75,  5, 79, 64, 16,  1, 76, 71,  6, 25, 50, 20, 18,
       84, 11, 28, 29, 14, 50, 68, 87, 87, 94, 96, 86, 13,  9,  7, 63, 61,
       22, 57,  1,  0, 60, 81,  8, 88, 13, 47, 72, 30, 71,  3, 70, 21])

In [83]:
t = np.random.randint(10, size=(3,4))
t

array([[0, 3, 4, 2],
       [0, 3, 5, 1],
       [2, 4, 3, 0]])

In [84]:
t.ndim

2

In [85]:
t.shape

(3, 4)

In [86]:
t.size

12

In [88]:
t.dtype

dtype('int64')

In [87]:
t.itemsize

8

In [89]:
t.nbytes

96

In [92]:
t8 = t.astype(np.int8)
t8

array([[0, 3, 4, 2],
       [0, 3, 5, 1],
       [2, 4, 3, 0]], dtype=int8)

In [93]:
t8.itemsize

1

In [94]:
t8.nbytes

12

In [167]:
np.arange(9, 0, -1)

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

### Array Slicing

In [95]:
arr = np.random.randint(0, 10, (5, 2))
arr

array([[6, 0],
       [7, 2],
       [8, 3],
       [0, 8],
       [4, 2]])

In [96]:
arr[:, 1]

array([0, 2, 3, 8, 2])

In [97]:
arr[3, 1]

8

In [98]:
arr[[1,3], 1]

array([2, 8])

In [99]:
arr[1:4:2, 1]

array([2, 8])

In [101]:
arr > 5

array([[ True, False],
       [ True, False],
       [ True, False],
       [False,  True],
       [False, False]])

In [100]:
arr[arr > 5] 

array([6, 7, 8, 8])

In [111]:
a = arr.copy()

a[a > 5] = 99
a

array([[99,  0],
       [99,  2],
       [99,  3],
       [ 0, 99],
       [ 4,  2]])

In [112]:
np.isnan(a)

array([[False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False]])

In [114]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [115]:
a[:5]

array([0, 1, 2, 3, 4])

In [116]:
a[5:]

array([5, 6, 7, 8, 9])

In [128]:
a[4:8]

array([4, 5, 6, 7])

In [129]:
a[::2]

array([0, 2, 4, 6, 8])

In [130]:
a[1::2]

array([1, 3, 5, 7, 9])

In [131]:
a[-3:]

array([7, 8, 9])

In [132]:
a[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [133]:
a[5::-1]

array([5, 4, 3, 2, 1, 0])

In [135]:
a[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [117]:
import pandas as pd

In [125]:
data = pd.DataFrame(np.random.randint(0, 10, (5, 2)))
data

0  1
0  3  5
1  6  7
2  5  1
3  7  0
4  2  8

In [127]:
data['1'][data>3] = 1000

KeyError: '1'

In [124]:
data

0     1
0     3  1000
1     3     2
2  1000  1000
3     0     3
4     3  1000

In [137]:
np.ones((2, 2, 2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [139]:
arr = np.random.randint(0, 10, (5, 2))
arr

array([[6, 9],
       [6, 9],
       [6, 0],
       [0, 2],
       [9, 6]])

In [142]:
print(np.sum(arr, axis=0))
print(np.sum(arr, axis=1))

[27 26]
[15 15  6  2 15]


In [145]:
np.argmax(arr, axis=0)

array([4, 0])

In [ ]:
np.nan

In [150]:
arr = np.random.randint(0, 5, (5, 2))
arr

array([[2, 4],
       [3, 4],
       [4, 0],
       [3, 2],
       [4, 3]])

In [151]:
np.unique(arr)

array([0, 2, 3, 4])

In [153]:
test = np.unique(arr, return_counts=True)
test

(array([0, 2, 3, 4]), array([1, 2, 3, 4]))

In [155]:
test[1]

array([1, 2, 3, 4])

In [156]:
unique, counts = np.unique(arr, return_counts=True)

In [157]:
unique

array([0, 2, 3, 4])

In [158]:
counts

array([1, 2, 3, 4])

### Broadcating of binary functions

In [159]:
arr = np.random.randint(0, 5, (5, 2))
arr2 = np.random.randint(0, 5, (5, 2))
print(arr)
print('----')
print(arr2)

[[4 2]
 [3 0]
 [2 1]
 [3 2]
 [0 1]]
----
[[4 1]
 [3 3]
 [1 2]
 [0 2]
 [4 0]]


In [160]:
arr + arr2

array([[8, 3],
       [6, 3],
       [3, 3],
       [3, 4],
       [4, 1]])

In [168]:
arr = np.random.randint(0, 5, (5, 2))
arr2 = np.random.randint(0, 5, (2, 5))
print(arr)
print('----')
print(arr2)

[[3 1]
 [1 4]
 [4 0]
 [2 1]
 [3 0]]
----
[[1 0 2 2 4]
 [3 2 2 2 0]]


In [169]:
arr + arr2

ValueError: operands could not be broadcast together with shapes (5,2) (2,5) 

In [171]:
arr2.T

array([[1, 3],
       [0, 2],
       [2, 2],
       [2, 2],
       [4, 0]])

In [170]:
arr + arr2.T

array([[4, 4],
       [1, 6],
       [6, 2],
       [4, 3],
       [7, 0]])

In [172]:
arr.flatten()

array([3, 1, 1, 4, 4, 0, 2, 1, 3, 0])

In [173]:
arr.ravel()

array([3, 1, 1, 4, 4, 0, 2, 1, 3, 0])

In [177]:
arr.reshape(1, 10)

array([[3, 1, 1, 4, 4, 0, 2, 1, 3, 0]])

In [196]:
list_1 = [1, 2, 3, 4, 5]
list_2 = []

In [182]:
for i in list_1:
    if i <= 3:
        list_2.append(i)
list_2

[1, 2, 3]

In [197]:
[list_2.append(i) for i in list_1 if i <= 3]
list_2

[1, 2, 3]