In [1]:
import numpy as np

In [3]:
def node_gini(node):
    _, p_node = np.unique(node, return_counts=True)
    p_node = p_node/node.shape[0]
    gini_node = 1-((p_node**2).sum())
    return gini_node

In [12]:
def split_gini(left, right):
    if (len(left) == 0) & (len(right) == 0):
        return "Erreur, left et right vide!"
    
    if len(left) == 0:
        return node_gini(right)
    
    if len(right) == 0:
        return node_gini(left)
    
    _, p_left = np.unique(left, return_counts=True)
    _, p_right = np.unique(right, return_counts=True)
    p_left = p_left/left.shape[0]
    p_right = p_right/right.shape[0]
    gini_left = 1-((p_left**2).sum())
    gini_right = 1-((p_right**2).sum())
    gini_left = (left.shape[0]/node.shape[0])*gini_left
    gini_right = (right.shape[0]/node.shape[0])*gini_right
    split_gini = gini_left+gini_right
    return split_gini

In [25]:
def split_all_gini(node):
    # return (left, right)
    
    gini = 1
    for i in range(len(node)):
        new_gini = split_gini(node[:i], node[i:])
        if new_gini < gini:
            gini = new_gini
            left = node[:i]
            right = node[i:]
    
    return (left, right)

In [26]:
node = np.array([0,0,0,0,1,1,1,1])
split_all_gini(node)

(array([0, 0, 0, 0]), array([1, 1, 1, 1]))

In [5]:
node = np.array([0,0,0,0,1,1,1,1])
node_gini(node)

0.5

In [6]:
left = np.array([0,0,0,1])
right = np.array([1,1,1,0])

split_gini(left, right)

0.375

In [23]:
gini = 1
for i in range(len(node)):
    new_gini = split_gini(node[:i], node[i:])
    print('i :', i)
    print('left :', node[:i])
    print('right :' , node[i:])
    print('gini :', split_gini(node[:i], node[i:]))
    print('---------')

i : 0
left : []
right : [0 0 0 0 1 1 1 1]
gini : 0.5
---------
i : 1
left : [0]
right : [0 0 0 1 1 1 1]
gini : 0.42857142857142866
---------
i : 2
left : [0 0]
right : [0 0 1 1 1 1]
gini : 0.3333333333333333
---------
i : 3
left : [0 0 0]
right : [0 1 1 1 1]
gini : 0.1999999999999999
---------
i : 4
left : [0 0 0 0]
right : [1 1 1 1]
gini : 0.0
---------
i : 5
left : [0 0 0 0 1]
right : [1 1 1]
gini : 0.1999999999999999
---------
i : 6
left : [0 0 0 0 1 1]
right : [1 1]
gini : 0.3333333333333333
---------
i : 7
left : [0 0 0 0 1 1 1]
right : [1]
gini : 0.42857142857142866
---------


In [24]:
gini = 1
for i in range(len(node)):
    new_gini = split_gini(node[:i], node[i:])
    if new_gini < gini:
        gini = new_gini
        n_left = node[:i]
        n_right = node[i:]
        
print('n_left :', n_left)
print('n_right :', n_right)

n_left : [0 0 0 0]
n_right : [1 1 1 1]


In [28]:
left

array([0, 1])

In [29]:
right

array([], dtype=float64)

In [30]:
left = np.array([0,0,0,1])
right = np.array([1,1,1,0])

left + right

array([1, 1, 1, 1])

In [31]:
np.concatenate([left, right])

array([0, 0, 0, 1, 1, 1, 1, 0])